# Generated by Django 4.1 on 2022-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('secret_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
