# Generated by Django 4.1 on 2022-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='PaymentIntend',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
