# Generated by Django 4.1 on 2022-09-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolor',
            old_name='color',
            new_name='color_hex',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
