# Generated by Django 4.1 on 2022-09-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_color_productcolor_color_hex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='color_name',
        ),
    ]
