# Generated by Django 4.1 on 2022-09-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_productcolor_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
